config/routes.rb
Rails.application.routes.draw do
	root to: 'welcome#dashboard'
	get "login" => "sessions#new", :as => "login"
	delete "/logout", to: 'sessions#destroy'
  resources :users, only: [:new, :create, :show, :index, :update, :edit] do
		resources :points, only: [:new, :show, :create]
	end
	resources :sessions, only: [:new, :create, :show]
	resources :rewards, only: [:index, :new, :create, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/linker.rb
class Linker
	def initialize(user, reward)
		UserReward.create(user: user, reward: reward)
	end
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
end

app/models/reward.rb
class Reward < ApplicationRecord
  has_many :user_rewards
  has_many :users, through: :user_rewards
  validates :title, :url, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :username, presence: true, uniqueness: true
	has_many  :points
	has_many  :user_rewards
	has_many 	:rewards, through: :user_rewards

	def self.authenticate(username, password)
		user = find_by_username(username)
    if user && user.password == password
      user
    else
      nil
    end
	end
	
	def point_subtract(number)
		number.times do |point, index|
			unredeemed_points[index].redeemed = true
		end
	end
		
	
	def unredeemed_points
		points.count{|point| !point.redeemed}
	end
end

app/models/user_reward.rb
class UserReward < ApplicationRecord
	belongs_to :reward
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
	def new
		@user = User.find(params[:user_id])
		@point = Point.new
	end
	
	def create
		@user = User.find(params[:user_id])
		@point = @user.points.new
		@point.save
		redirect_to users_path
	end
		
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
	def index
		@user = User.find(session[:user_id])
		@rewards = Reward.all
	end
	
	def show
		@reward = Reward.find(params[:id])
	end
	
	def new
		@reward = Reward.new
	end
	
	def create
		@reward = Reward.new(reward_params)
		if @reward.save
			redirect_to user_path(@user)
		else
			render :new
		end
	end
	
	def update
		@reward = Reward.find(params[:id])
		if current_user.unredeemed_points >= @reward.cost
			Linker.new(current_user, @reward)
			flash[:success] = "You added #{@reward.title} to your rewards"
			current_user.point_subtract(@reward.cost)
		else
			flash[:failure] = "You don't have enough points to add #{@reward.title}"
			redirect_to rewards_path
		end
	end

	private
	def reward_params
		params.require(:reward).permit(:title, :url, :cost)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	
	def create
		user = User.find_by(username: params[:username])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to user_path(user)
		else
			redirect_to login_path
		end
	end
	
	def destroy
		session.clear
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to  user_path(@user)
		else
			render :new
		end
	end
	
	def show
		@user = User.find(params[:id])
	end
	
	def index
		@users = User.all
	end
	
	

	
	private
	
	def user_params
		params.require(:user).permit(:username, :password)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def dashboard
		@users = User.all
		@user = User.find(session[:user_id]) if session[:user_id]
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PointMaster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/points/new.html.erb
<%= form_for [@user, @point] do |f| %>
<%= f.submit %>
<% end %>

app/views/rewards/index.html.erb
<h3 class = 'center'>Welcome to the super fun time awesome rewards store!</h3>
<h4>Pick your fabulous prizes here:</h4>


		<% @rewards.each do |reward| %>
			<p><%= reward.title %></p>
			<div>
				<%= link_to image_tag(reward.url), reward_path(reward) %>
			</div>
		<% end %>

<% if current_user.admin %>
	<%= link_to "New Reward", new_reward_path %>
<% end %>

app/views/rewards/new.html.erb
<%= form_for(@reward) do |f| %>
	<%= f.label :title %>
	<%= f.text_area :title %>
	<%= f.label :url %>
	<%= f.text_area :url %>
	<%= f.submit %>
<% end %>

app/views/rewards/show.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		<h1 class= 'center'> <%= @reward.title %> </h1>
		<div class= 'center'>
			<%= image_tag(@reward.url) %> <br />
			<%= link_to "Add Reward", reward_path(@reward), action: 'update', method: 'patch' %>
		</div>
	</body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		<%= link_to "Back to Dashboard", root_path %> <br /><br />
	<% @users.each do |user| %>
  <li >
    <%= link_to user.username, user_path(user) %> <br />
		Points: <%= user.points.count %>
		<%= link_to "Add Point", user_points_path(user), method: 'post' %> 
  </li>
	<br />
  <% end %>
	</body>
</html>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
	<%= f.label :username %>
	<%= f.text_area :username %>
	<%= f.label :password %>
	<%= f.text_area :password %>
	<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		<p>
			<h4 class= 'center'>Hello <%= @user.username %>! </br></h4>
			You have <%= @user.unredeemed_points %>  Points! <br />
			You've spent <%= @user.points.count - @user.unredeemed_points %> Points on
			some sweet rewards!
		</p>
		<p>
			Your rewards: <br/> <% @user.rewards.each do |reward| %>
			<h5><%= reward.title %> <br /> <div>
				<img src=<%= reward.url %>></h5>
			</div> 
			<% end %>
		</p>
		<p class='center'>
			<%= link_to "Rewards Store", rewards_path %> <br />
			<%= link_to "Dashboard", root_path %>
		</p>
	</body>
</html>

app/views/welcome/dashboard.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		<h2 class='center'>WELCOME TO POINT MASTER</h2>
		<h4 class='center'>Where Everyone is a Winner! </h4>
			<p class= 'center'>
				<% if !current_user %>
				<%= link_to "Create New User", new_user_path %> <br />
				<%= link_to "Login", login_path %>
				
				<% elsif current_user.admin %>
				<%= link_to "Create New User", new_user_path %> <br />
				<%= link_to "Logout", logout_path, method: :delete %> <br />
				<%= link_to "View users/Assign a new point", users_path %> <br />
				<span><%= link_to "Your points and Rewards", user_path(@user) %> </span> <br />
				<%= link_to "Rewards Store", rewards_path %> <br />
				
				<% else %>
				<%= link_to "Logout", logout_path, method: :delete %> <br />
				<span><%= link_to "Your points and Rewards", user_path(@user) %> </span> <br />
				<%= link_to "Rewards Store", rewards_path %> <br />
				<% end %>
			</p>
	</body>
</html>